### ISSUE TITLE
Verbose fail in subtest

### ISSUE THREAD

**Issue by janlimpens** [houseabsolute/Test2-Plugin-NoWarnings#4]
Right now, my Tests2::V0 subtests fail upon a warning, but give no explanation why ("Failed test 'subtest_name'"). 
I prefer the behavior as without a subtest ('Warning: something's wrong at ...'). It might be an issue with subtest, I cannot tell.

**Comment by autarch** [comment]
Can you share the code that causes this? Without that I can't really tell what's going on.

**Comment by janlimpens** [comment]
I seem unable to isolate the issue, so it will be some error on my side.

However, I still think, the output is too discreet:

```perl
#!/usr/bin/env perl
use v5.38;

package X {
    sub frobnicate() {
        my $x;
        $x =~ /bla/;
    }
}

use Test2::V0;
use Test2::Plugin::NoWarnings echo => 1;

X::frobnicate();
ok undef, 'some reason';

done_testing();
```

produces:

```sh
> prove ~/no_warnings.t 
/home/username/no_warnings.t .. 1/? Use of uninitialized value $x in pattern match (m//) at /home/username/no_warnings.t line 7.

# Failed test 'some reason'
# at /home/username/no_warnings.t line 15.
# Seeded srand with seed '20240405' from local date.
/home/username/no_warnings.t .. Dubious, test returned 2 (wstat 512, 0x200)
Failed 2/2 subtests 

Test Summary Report
-------------------
/home/username/no_warnings.t (Wstat: 512 (exited 2) Tests: 2 Failed: 2)
  Failed tests:  1-2
  Non-zero exit status: 2
Files=1, Tests=2,  0 wallclock secs ( 0.03 usr  0.01 sys +  0.12 cusr  0.02 csys =  0.18 CPU)
Result: FAIL
```

The ok is clearly stated as failed, the warning only when we run prove with the -v parameter.
The only indication that no_warnings failed is the inclusion of the warning in STDERR (explicit via echo => 1) and there is no guarantee for this to be set.
In my opinion, it is insufficient to quickly grok the reason of the failure.
I think there should be a clearly stated failed test at the end (if so). Something along the lines of:

```
Failed test no_warnings line n '$warning''
```
